// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqrqmfejinsqisnjcrls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxcnFtZmVqaW5zcWlzbmpjcmxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3ODM4MzIsImV4cCI6MjA2MTM1OTgzMn0.oqlFyG8l2bStYyjM1tu2qirZEn5moyZnBZMXs3UgnoY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);